version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python main.py"
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default
      - main
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python consumer.py"
    depends_on:
      - db
    networks:
      - default
      - main
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    networks:
      - main
networks:
  default:
    external:
      name: rabbitmq
  main:
    internal: true
volumes:
  dbdata:
    name: main-data
    driver: local
